name: uts_mobile_banking
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.0.10
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.7+3
  lottie: ^3.1.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0 # Dependency ikon aplikasi

flutter:
  uses-material-design: true
  assets:
    - assets/images/Anime Hijau.jpg # Path ke gambar splash screen
    - assets/images/Sumi_Mobile_PP.jpg
    - assets/images/Splash.jpg
    - assets/images/spay.jpg
    - assets/images/gopay.png
    - assets/images/dana.png
    - assets/images/astrapay.jpg
    - assets/images/i.saku.png
    - assets/images/ovo.png
    - assets/images/linkaja.png
    - assets/images/etoll.png
    - assets/images/flazz.png
    - assets/images/background2.jpg
    - assets/animations/confetti.json
    - assets/animations/paymentsuccess.json
    - assets/animations/goodgood.json
    - assets/images/bca.jpg
    - assets/images/bri.jpg
    - assets/images/cimbniaga.jpg
    - assets/images/citibank.jpg
    - assets/images/danamon.jpg
    - assets/images/mandiri.jpg
    - assets/images/mega.jpg
    - assets/images/panin.jpg
    - assets/images/permata.jpg
    - assets/images/seabank.jpg
    - assets/images/uob.jpg
    - assets/images/nav.jpg
    - assets/images/kartudebit.png
    - assets/images/bg.jpg
    - assets/images/login_screen_bg.png
    - assets/images/ads1.jpeg
    - assets/images/ads2.jpeg
    - assets/images/ads3.jpeg
    - assets/images/ad1.jpeg
    - assets/animations/Animation - 1728215250294.json


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Sumi_Mobile_PP.jpg" 