name: uts_mobile_banking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.0.10
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0 # Dependency ikon aplikasi
  flutter_native_splash: ^2.0.0 # Dependency splash screen

flutter:
  uses-material-design: true
  assets:
    - lib/Anime Hijau.jpg # Path ke gambar splash screen

    - assets/images/spay.jpg
    - assets/images/gopay.png
    - assets/images/dana.png
    - assets/images/astrapay.jpg
    - assets/images/i.saku.png
    - assets/images/ovo.png
    - assets/images/linkaja.png
    - assets/images/etoll.png
    - assets/images/flazz.png

flutter_native_splash:
  color: "#FFFFFF" # Warna splash screen
  image: "lib/Anime Hijau.jpg" # Path splash screen

flutter_icons:
  android: true
  ios: true
  image_path: "lib/Anime Hijau.jpg" # Ganti dengan path ke gambar ikon Anda
