name: uts_mobile_banking
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.0.10
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.7+3
  lottie: ^3.1.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0 # Dependency ikon aplikasi
  flutter_native_splash: ^2.0.0 # Dependency splash screen

flutter:
  uses-material-design: true
  assets:
    - lib/Anime Hijau.jpg # Path ke gambar splash screen
    - lib/SUMI MOBILE.jpg
    - lib/Splash.jpg
    - assets/images/spay.jpg
    - assets/images/gopay.png
    - assets/images/dana.png
    - assets/images/astrapay.jpg
    - assets/images/i.saku.png
    - assets/images/ovo.png
    - assets/images/linkaja.png
    - assets/images/etoll.png
    - assets/images/flazz.png
    - assets/images/background2.jpg
    - assets/animations/confetti.json
    - assets/animations/paymentsuccess.json
    - assets/images/bca.jpg
    - assets/images/bri.jpg
    - assets/images/cimbniaga.jpg
    - assets/images/citibank.jpg
    - assets/images/danamon.jpg
    - assets/images/mandiri.jpg
    - assets/images/mega.jpg
    - assets/images/panin.jpg
    - assets/images/permata.jpg
    - assets/images/seabank.jpg
    - assets/images/uob.jpg
    - assets/images/nav.jpg
    - assets/images/kartudebit.png
    - assets/images/bg.jpg
    - assets/images/login_screen_bg.png

flutter_native_splash:
  image: lib/Anime Hijau.jpg
  color: "#ffffff" # Warna background splash screen
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "lib/SUMI MOBILE.jpg" # Ganti dengan path ke gambar ikon Anda
